### ISSUE TITLE
Connected timeout

### ISSUE THREAD

**Issue by camolin3** [gchudnov/w3c-css#1]
There is someone, somewhere, saying that has been banned from the W3C service.

http://stackoverflow.com/questions/29484947/node-js-css-validation-w3c-banned-me/29633064#29633064

Is there any possibility to add an option to set a max amount of request? Or maybe an easy way to install the CSS Validator, and set this package to use the local server instead of the W3C's?

**Comment by gchudnov** [comment]
Pardon, not sure I understand about "max amount of requests". Could you add some more details?

And yes, I think it is possible to set up a private server. Here is the source: https://jigsaw.w3.org/css-validator/DOWNLOAD.html.
Guess I can try to install locally and write some guidelines.

Why don't you set the timeout between the requests? E.g. with the [async](https://github.com/caolan/async) library and the `setTimeout` function?

**Comment by camolin3** [comment]
I just read your answer in SO. I didn't know which was the reason to be banned and I though it was because a limit over _how many documents you could send in a minute_.

I think there is good solution to use the async + setTimeout solution. It could be documented as a "recipe" for people using gulp.

**Comment by gchudnov** [comment]
It looks the restriction is applied on a web server. I wasn't able to find any restriction-related code in the source-code of the validator.

To mitigate this issue:
* Added some [comments](https://github.com/gchudnov/w3c-css#note) and an [example](https://github.com/gchudnov/w3c-css/blob/master/examples/validate-multiple.js).
* Placed `setTimeout` right into the [gulp-plugin](https://github.com/gchudnov/gulp-w3c-css/blob/master/index.js#L32).

I hope this helps.
