### ISSUE TITLE
css3 + svg profile not supported

### ISSUE THREAD

**Issue by mayank-kc** [gchudnov/w3c-css#11]
When I tried validating svg css properties like stroke, stroke-width it raised the parse-error. I checked on the w3c validation service, they have another profile setting of css3 + svg. If you can mention about a workaround or add the support for that profile too - that will be great, thanks.

**Comment by gchudnov** [comment]
@mayank-kc

thank you for the information, will check / update

**Comment by mayank-kc** [comment]
I cross checked it on their documentation [here](https://jigsaw.w3.org/css-validator/manual.html#paramprofile) and we can pass these profiles - `css1, css2, css21, css3, svg, svgbasic, svgtiny, mobile, atsc-tv, tv, none` in their validation service profile param. Not sure if they are providing us to implement more than 1 profile at the same time like they have on their website with a css3+svg profile option [here](https://jigsaw.w3.org/css-validator/#validate_by_uri+with_options). Let me know if you can find something, thanks!

**Comment by mayank-kc** [comment]
@gchudnov I found the solution! W3C validator's documentation haven't really mentioned about this. I inspected w3c validator's API request that they do for a 'css3 + svg' profile selection and the profile value was `svg3css`. When I passed profile as `css3svg` it works just fine for svg css properties too! It will be good if you can mention about this in the README, thanks!
