### ISSUE TITLE
set error and warning as falsy when there are no errors nor warnigs

### ISSUE THREAD

**Issue by jfoclpf** [gchudnov/w3c-css#12]
This should work but it does not, it seems when there are no errors data.errors is an empty array, of I could make `data.errors.length` but it would be more clear like this:

```js
  validator.validate(href, function(err, data) {
    if(err) {
      console.log('Failed to process: ' + href, err);
    } else if (data.errors) {
      console.log('validation errors on ' + href, data.errors);
    } else if (data.warnings) {
      console.log('validation warnings on ' + href, data.warnings);
    }
  });
```

**Comment by gchudnov** [comment]
Hi @jfoclpf 
could you provide a bit more details on what exactly is not working?
I'm a bit confused on how to reproduce thje error.

**Comment by jfoclpf** [comment]
everything is working, just to mention that when no errors are present `data.errors` should be falsy and not merely an empty array because empty arrays are not falsy

But maybe I'm being too picky
