### ISSUE TITLE
err connect host

### ISSUE THREAD

**Issue by miton18** [gchudnov/w3c-css#4]
Hi, just an error when I want to go to https://jigsaw.w3.org/

ERR_CONNECTION_TIMED_OUT

So w3c-css can't validate...

**Comment by gchudnov** [comment]
Hi miton18,

the library depends on a 3rd party service.
According to the [manual](http://jigsaw.w3.org/css-validator/manual.html):

> Note: If you wish to call the validator programmatically for a batch of documents, 
> please make sure that  your script will sleep for at least 1 second between requests. 
> The CSS Validation service is a free, public service for all, your respect is appreciated. thanks.

It looks you were temporarily banned by the service. I don't know the exact rules or duration they enforce to ban an IP.

There is hardly anything I can do in the library to prevent that, sorry.
Try to reduce the frequency of validation requests when the ban expires.

**Comment by gchudnov** [comment]
To avoid timeout issues, please run the validation server locally.

## w3c-css v2.0.0:

Added an option to specify a custom server:
* `server` - the "IP:PORT" string or the [URL object](https://nodejs.org/api/url.html) of a custom validation server, e.g, '172.17.0.2:8080' or { host: '172.17.0.2:8080' } or { hostname: '172.17.0.2:8080', port: 8080 }

Added [npm run scripts](https://github.com/gchudnov/w3c-css#private-css-validator) to run the validation server locally in a docker container. 

An updated readme is [here](https://github.com/gchudnov/w3c-css)

Let me know if there are any problems.
