### ISSUE TITLE
Validate css file on localhost

### ISSUE THREAD

**Issue by jfoclpf** [gchudnov/w3c-css#6]
Do you have any function to validate on `localhost` ?
I know I could read the file data with `fs` and then pass it to `options.text` but my css may be dynamically generated

What do you think about this function?

```js
// pathname is for example '/css/style.css'
function validateOnLocalhost (pathname, port, callback) {
  const request = require('request')
  var uri = 'http://localhost:' + port + pathname

  request({ uri: uri }, function (err, response, body) {
    if (err) {
      callback(Error(err))
      return
    }

    let options = {
      text: body
    }

    validator.validate(options)
      .on('error', function (err) {
        callback(Error(err))
      })
      .on('validation-error', function (data) {
        console.log(`Error on ${url}\n`.error, data)
        callback(Error('Found css error on ' + url))
      })
      .on('validation-warning', function (data) {
        console.log(`Warning on ${url}\n`.error, data)
        callback(Error('Found css error on ' + url))
      })
      .on('end', function () {
        // since is a public service we should wait 1 s between requests
        // https://www.npmjs.com/package/w3c-css#public-css-validator
        setTimeout(function () { callback() }, 1000)
      })
  })
}
```

**Comment by gchudnov** [comment]
Hi @jfoclpf 
hm.. I'm slightly confused, since `validator.validate(str)` function accepts a URL to the resource, e.g.:
```
validator.validate('https://github.com/')
```
so the required functionality should be available out of the box, you don't need to read the body and pass it as text.

[here](https://github.com/gchudnov/w3c-css#public-css-validator) is an example that validates several URLs.

Is that working for you?

**Comment by jfoclpf** [comment]
I know, but normally these W3C wrapers do not work for localhost. I will give it a try directly out of the box to localhost.

**Comment by gchudnov** [comment]
ah, sorry, got it.
in this case, yes, it will be a problem and it is better to send css as text like in your example.

**Comment by jfoclpf** [comment]
I found this function very relevant because this allows us to test the css locally without sending it to the www (of course the W3C servers will have its content, but just its servers). 

You may want to integrate this function to your package at your will. At least, it would be less code on my side, which I would appreciate :)

Maybe through an extra `option.localhost = { isLocalhost: true, port: 3000 }`
