### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jfoclpf** [gchudnov/w3c-css#7]
I don't know why, maybe because I forced the update of all dependencies of my project, but the module stopped working

On the function `validate` none of the triggers nor the callback, are called

```js
    let options = {
      profile: 'css3svg',
      warning: 'no', // medium warnings
      text: body // some valid css
    }

    console.log('validating...') // this is printed
    validator.validate(options)
      .on('error', function (err) {
        console.log('Error: ' + err) // not printed
      })
      .on('validation-error', function (data) {
        console.log('on validation-error') // not printed
      })
      .on('validation-warning', function (data) {
        console.log('on validation-warning') // not printed
      })
      .on('end', function () {
        console.log('on end') // not printed
        // since is a public service we should wait 1 s between requests
        // https://www.npmjs.com/package/w3c-css#public-css-validator
        setTimeout(function () { callback() }, 1100)
      })
```

```
npm list nopt once request sax
autocosts@6.0.16 /home/jfolpf/autocosts
├─┬ eslint@5.16.0
│ └─┬ glob@7.1.3
│   ├─┬ inflight@1.0.6
│   │ └── once@1.4.0  deduped
│   └── once@1.4.0  deduped
├─┬ html-validator@3.1.3
│ └── request@2.88.0  deduped
├─┬ is-online@8.1.0
│ └─┬ got@9.6.0
│   └─┬ get-stream@4.1.0
│     └─┬ pump@3.0.0
│       ├─┬ end-of-stream@1.4.1
│       │ └── once@1.4.0  deduped
│       └── once@1.4.0  deduped
├─┬ libxmljs@0.19.5
│ └─┬ node-pre-gyp@0.11.0
│   ├─┬ needle@2.2.4
│   │ └── sax@1.2.4  deduped
│   └── nopt@4.0.1  deduped
├─┬ phantomjs-prebuilt@2.1.16
│ └── request@2.88.0  deduped
├── request@2.88.0 
└─┬ w3c-css@2.0.2
  ├── nopt@4.0.1 
  ├── once@1.4.0 
  ├── request@2.88.0  deduped
  └── sax@1.2.4 
```

Any ideas? Can you confirm that this works with the last version of request?

**Comment by gchudnov** [comment]
Hi @jfoclpf 
If you use the external server and for validation and do not limit the frequency it blocks you temporarily.
To avoid that run your local server via docker.

**Comment by jfoclpf** [comment]
I always limit the frequency, not less than 1 second between requests. But
how can I know for sure that I was blocked by the server? Shouldn't it be
more verbose?

**Comment by gchudnov** [comment]
It's up to the server to limit the requests. Not sure about the policy they implement to restrict the frequency of requests.

Shouldn't it be more verbose?
^^
as soon as the restricting policy implemented on the server side, there are no many options to handle that on the client, besides setting up some artificial timeout, e.g. 10 seconds.

**Comment by jfoclpf** [comment]
I really cannot make it work, already waited 1 day to be sure and still
doesn't work
I always leave 1 second between requests! Maybe I have to use local server
via docker.

João Pimentel Ferreira <http://joaopimentel.eu>

**Comment by gchudnov** [comment]
yes, try the local server.
I really don't know the policy the server uses to restrict the frequency of requests :(

**Comment by jfoclpf** [comment]
thanks
João Pimentel Ferreira <http://joaopimentel.eu>

**Comment by gchudnov** [comment]
please let me know if there are any problems or it works for you

**Comment by jfoclpf** [comment]
Thanks a lot for the help!
I can make it work from my remote server, not from my home machine, thus
your module is working fine :)
It seems I was blocked, don't know why!
Cheers and thanks again

João Pimentel Ferreira <http://joaopimentel.eu>

**Comment by gchudnov** [comment]
you're welcome!

**Comment by jfoclpf** [comment]
it is working
